/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ComandoDAO;
import java.util.ArrayList;
import model.Comando;
/**
 *
 * @author Rennan Cavalcante
 */
public class viewCadComando extends javax.swing.JFrame {

    /**
     * Creates new form CadComando
     */
    public viewCadComando() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCadastroComandos = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        lSintaxe = new javax.swing.JLabel();
        lDescricao = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfSintaxe = new javax.swing.JTextField();
        tfDescricao = new javax.swing.JTextField();
        tfCadastrar = new javax.swing.JButton();
        tfAjuda = new javax.swing.JButton();
        tfCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lCadastroComandos.setText("CADASTRO DE COMANDOS");

        lNome.setText("Nome ");

        lSintaxe.setText("Sintaxe");

        lDescricao.setText("Descriçao");

        tfDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescricaoActionPerformed(evt);
            }
        });

        tfCadastrar.setText("Cadastrar");
        tfCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCadastrarActionPerformed(evt);
            }
        });

        tfAjuda.setText("Ajuda");
        tfAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAjudaActionPerformed(evt);
            }
        });

        tfCancelar.setText("Cancelar");
        tfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lCadastroComandos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(tfAjuda)
                                .addGap(18, 18, 18)
                                .addComponent(tfCadastrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lSintaxe, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lDescricao, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfSintaxe)
                                    .addComponent(tfNome)
                                    .addComponent(tfDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lCadastroComandos)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSintaxe)
                    .addComponent(tfSintaxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDescricao)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCadastrar)
                    .addComponent(tfAjuda)
                    .addComponent(tfCancelar))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAjudaActionPerformed

    private void tfDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescricaoActionPerformed

    private void tfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCancelarActionPerformed
        setVisible(false);
        new viewComandos().setVisible(true);
    }//GEN-LAST:event_tfCancelarActionPerformed

    private void tfCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCadastrarActionPerformed
        String comandoNomeAtual = tfNome.getText();
        String comandoSintaxeAtual = tfSintaxe.getText();
        String comandoDescricaoAtual = tfDescricao.getText();
        
        Comando comandoAtual = new Comando();
        ComandoDAO cmddao = new ComandoDAO();
        
        comandoAtual.setNome(tfNome.getText());
        comandoAtual.setDescricao(tfDescricao.getText());
        comandoAtual.setSintaxe(tfSintaxe.getText());
        
        view.viewComandos.comandos.add(comandoAtual);
        cmddao.cadastrar();
        System.out.println(view.viewComandos.comandos);
        
        tfNome.setText("");
        tfSintaxe.setText("");
        tfDescricao.setText("");
        
        
        
    }//GEN-LAST:event_tfCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCadComando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCadComando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCadComando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCadComando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCadComando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lCadastroComandos;
    private javax.swing.JLabel lDescricao;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lSintaxe;
    private javax.swing.JButton tfAjuda;
    private javax.swing.JButton tfCadastrar;
    private javax.swing.JButton tfCancelar;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSintaxe;
    // End of variables declaration//GEN-END:variables
}
