/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Comando;
import static view.viewComandos.comandos;


/**
 *
 * @author Rennan Cavalcante
 */
public class viewAtualizarComando extends javax.swing.JFrame {

    /**
     * Creates new form viewAtualizarComando
     */
    public viewAtualizarComando() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btDeletarAt = new javax.swing.JButton();
        lAtualizacaoComandos = new javax.swing.JLabel();
        lNomeAt = new javax.swing.JLabel();
        tfNomeAt = new javax.swing.JTextField();
        lSintaxeAt = new javax.swing.JLabel();
        tfSintaxeAt = new javax.swing.JTextField();
        lDescricaoAt = new javax.swing.JLabel();
        tfDescricaoAt = new javax.swing.JTextField();
        btAtualizarAt = new javax.swing.JButton();

        btDeletarAt.setText("Deletar");
        btDeletarAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarAtActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lAtualizacaoComandos.setText("ATUALIZACAO DE COMANDO");

        lNomeAt.setText("Nome ");

        lSintaxeAt.setText("Sintaxe");

        lDescricaoAt.setText("Descriçao");

        tfDescricaoAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescricaoAtActionPerformed(evt);
            }
        });

        btAtualizarAt.setText("Atualizar");
        btAtualizarAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarAtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lAtualizacaoComandos))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btAtualizarAt)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lNomeAt, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lSintaxeAt, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lDescricaoAt, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfSintaxeAt)
                                .addComponent(tfNomeAt)
                                .addComponent(tfDescricaoAt, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lAtualizacaoComandos)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomeAt)
                    .addComponent(tfNomeAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSintaxeAt)
                    .addComponent(tfSintaxeAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDescricaoAt)
                    .addComponent(tfDescricaoAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btAtualizarAt)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDescricaoAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescricaoAtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescricaoAtActionPerformed

    private void btDeletarAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarAtActionPerformed
        Comando atualizaComando = new Comando();
        
        atualizaComando.setNome(tfNomeAt.getText());
        atualizaComando.setSintaxe(tfSintaxeAt.getText());
        atualizaComando.setDescricao(tfDescricaoAt.getText());
        
        for (Comando c:comandos){
            if(c.getNome().equals(atualizaComando.getNome())){
                comandos.remove(c);
                System.out.println(comandos);
            }
            
        }
        setVisible(false);
        new viewComandos().setVisible(true);
        
    }//GEN-LAST:event_btDeletarAtActionPerformed

    private void btAtualizarAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarAtActionPerformed
        Comando atualizaComando = new Comando();
        
        atualizaComando.setNome(tfNomeAt.getText());
        atualizaComando.setSintaxe(tfSintaxeAt.getText());
        atualizaComando.setDescricao(tfDescricaoAt.getText());
        
        for (Comando c:comandos){
            if(c.getNome().equals(atualizaComando.getNome())){
                comandos.remove(c);
                System.out.println(comandos);

                c.setNome(atualizaComando.getNome());
                c.setSintaxe(atualizaComando.getSintaxe());
                c.setDescricao(atualizaComando.getDescricao());
                comandos.add(c);
                System.out.println(comandos);
 
            }
        }
        setVisible(false);
        new viewComandos().setVisible(true);
 
    }//GEN-LAST:event_btAtualizarAtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAtualizarComando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAtualizarComando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAtualizarComando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAtualizarComando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAtualizarComando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizarAt;
    private javax.swing.JButton btDeletarAt;
    private javax.swing.JLabel lAtualizacaoComandos;
    private javax.swing.JLabel lDescricaoAt;
    private javax.swing.JLabel lNomeAt;
    private javax.swing.JLabel lSintaxeAt;
    private javax.swing.JTextField tfDescricaoAt;
    private javax.swing.JTextField tfNomeAt;
    private javax.swing.JTextField tfSintaxeAt;
    // End of variables declaration//GEN-END:variables
}
